config/routes.rb
Rails.application.routes.draw do
  # Use for login and autorize all resource
  use_doorkeeper do
    # No need to register client application
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users,
             only: [ :sessions, :passwords, :confirmation ],
             skip_helpers: true,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }
  resources :users do
    member do
      get :activate
    end
  end
  resources :categories
  resources :achievements

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
           registrations: 'api/v1/users/registrations',
       }, skip: [:sessions, :password]
    end
  end

  namespace :api do
    namespace :v1 do
      resource :dashboard
      resources :leagues do
        collection do
          get :pending
        end
      end
      resource :categories
      resources :achievements
      resources :user_achievements
      resource :profiles
    end
  end

  root to: 'dashboard#index'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_achievements

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/api/v1/users/registrations_controller.rb
class Api::V1::Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :doorkeeper_authorize!, only: [:create], raise: false
  skip_before_action :verify_authenticity_token

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save

    if resource.persisted?
      if resource.active_for_authentication?
        # set_flash_message! :notice, :signed_up
        # To avoid login comment out sign_up method
        # sign_up(resource_name, resource)
        render json: resource # , location: after_sign_up_path_for(resource)
      else
        # set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        render json: resource # , location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  private

  def sign_up_params
    ActiveModelSerializers::Deserialization.jsonapi_parse(params)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'empty'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  # def create
  #   self.resource = warden.authenticate!(auth_options)
  #   byebug
  #   if resource.is_admin?
  #     set_flash_message!(:notice, :signed_in)
  #     sign_in(resource_name, resource)
  #     yield resource if block_given?
  #     respond_with resource, location: after_sign_in_path_for(resource)
  #   else
  #     set_flash_message!(:warning, :no_admin)
  #   end
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_admin
  before_action :set_user, only: [:edit, :update, :destroy, :activate]

  def index
    @users = User.page(params[:page]).with_deleted
  end

  def edit
  end

  def update
    if @user.update(update_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = 'User was successfully destroy.'
    redirect_to users_path
  end

  def activate
    @user.restore
    flash[:notice] = 'User was successfully activated.'
    redirect_to users_path
  end

  private

  def set_user
    @user = User.where(id: params[:id]).with_deleted.first
  end

  def update_params
    params.require(:user).permit(:email, :first_name, :last_name, :is_admin)
  end

  def redirect_unless_admin
    unless current_user.is_admin?
      redirect_to root_path
    end
  end

end

app/views/users/edit.html.erb
<%= form_for(@user)do |f| %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6 border-right">
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :is_admin %>
          <%= f.check_box :is_admin, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
      <%= f.submit "Update", class: "btn btn-primary float-right" %>
    </div>
<% end %>

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Admin?</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= user.deleted? ? 'bg-danger' : '' %>">
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.is_admin? ? 'Yes' : 'No' %></td>
        <td>
          <% if user.deleted? %>
            <span>
              <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i> Activate".html_safe, activate_user_path(user), class: 'btn btn-sm btn-outline-warning', data: {confirm: "Are you sure?"} %>
            </span>
          <% else %>
            <span>
              <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_user_path(user), class: 'btn btn-sm btn-primary' %>
            </span>
            <span>
              <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i> Delete".html_safe, user_path(user), method: :delete, class: 'btn btn-sm btn-outline-danger', data: {confirm: "Are you sure?"} %>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="apple_pagination mx-auto">
  <%= paginate @users, :container => false %>
</div>