config/routes.rb
Rails.application.routes.draw do
  # Use for login and autorize all resource
  use_doorkeeper do
    # No need to register client application
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users,
             only: [ :sessions, :passwords, :confirmation ],
             skip_helpers: true,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }
  resources :users do
    member do
      get :activate
    end
  end
  resources :categories
  resources :achievements

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
           registrations: 'api/v1/users/registrations',
       }, skip: [:sessions, :password]
    end
  end

  namespace :api do
    namespace :v1 do
      resource :dashboard
      resources :leagues do
        collection do
          get :pending
        end
      end
      resource :categories
      resources :achievements
      resources :user_achievements
      resource :profiles
    end
  end

  root to: 'dashboard#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  acts_as_paranoid
  
  belongs_to :category

  has_many :user_achievements
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :redirect_unless_admin
  before_action :set_achievement, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.page(params[:page])
  end

  def new
    @achievement = Achievement.new
  end

  def edit
  end

  def create
    if Achievement.create(update_params)
      flash[:notice] = 'Achievement was successfully updated.'
      redirect_to achievements_path
    else
      flash[:error] = "Achievement not created"
      render :new
    end
  end

  def update
    if @achievement.update(update_params)
      flash[:notice] = 'Achievement was successfully updated.'
      redirect_to achievements_path
    else
      flash[:error] = @achievement.errors.full_messages
      render :edit
    end
  end

  def destroy
    @achievement.destroy
    flash[:notice] = 'Achievement was successfully destroy.'
    redirect_to achievements_path
  end

  private

  def set_achievement
    @achievement = Achievement.find(params[:id])
  end

  def update_params
    params.require(:achievement).permit(:name, :points, :category_id)
  end

  def redirect_unless_admin
    unless current_user.is_admin?
      redirect_to root_path
    end
  end

end

app/controllers/api/v1/achievements_controller.rb
class Api::V1::AchievementsController < Api::V1::ApplicationController

  def show
    @achievements = Achievement.where(category_id: params[:id])
    render json: @achievements, each_serializer: AchievementSerializer
  end
  
end

app/views/achievements/edit.html.erb
<%= form_for(@achievement)do |f| %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :points %>
          <%= f.text_field :points, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {class: 'form-control'} %>
        </div>
      </div>
      <%= f.submit "Update", class: "btn btn-primary ml-3" %>
    </div>
  </div>
<% end %>

app/views/achievements/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Category</th>
      <th>Points</th>
      <th colspan="2">
        <span>
          <%= link_to "<i class='fa fa-plus' aria-hidden='true'></i> Create".html_safe, new_achievement_path, class: 'btn btn-sm btn-success' %>
        </span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @achievements.each do |achievement| %>
      <tr>
        <td><%= achievement.id %></td>
        <td><%= achievement.name %></td>
        <td><%= achievement.category.name %></td>
        <td><%= achievement.points %></td>
        <td>
          <span>
            <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_achievement_path(achievement), class: 'btn btn-sm btn-primary' %>
          </span>
          <span>
            <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i> Delete".html_safe, achievement_path(achievement), method: :delete, class: 'btn btn-sm btn-outline-danger', data: {confirm: "Are you sure?"} %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="apple_pagination mx-auto">
  <%= paginate @achievements, :container => false %>
</div>

app/views/achievements/new.html.erb
<%= form_for(@achievement)do |f| %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :points %>
          <%= f.text_field :points, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {class: 'form-control'} %>
        </div>
      </div>
      <%= f.submit "Create", class: "btn btn-primary ml-3" %>
    </div>
  </div>
<% end %>