config/routes.rb
Rails.application.routes.draw do
  # Use for login and autorize all resource
  use_doorkeeper do
    # No need to register client application
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users,
             only: [ :sessions, :passwords, :confirmation ],
             skip_helpers: true,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }
  resources :users do
    member do
      get :activate
    end
  end
  resources :categories
  resources :achievements

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
           registrations: 'api/v1/users/registrations',
       }, skip: [:sessions, :password]
    end
  end

  namespace :api do
    namespace :v1 do
      resource :dashboard
      resources :leagues do
        collection do
          get :pending
        end
      end
      resource :categories
      resources :achievements
      resources :user_achievements
      resource :profiles
    end
  end

  root to: 'dashboard#index'
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < Api::V1::ApplicationController

  def show
    @categories = Category.all
    render json: @categories, each_serializer: CategorySerializer
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :redirect_unless_admin
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    if Category.create(update_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to categories_path
    else
      flash[:error] = "Category not created"
      render :new
    end
  end

  def update
    if @category.update(update_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to categories_path
    else
      flash[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'category was successfully destroy.'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def update_params
    params.require(:category).permit(:name)
  end

  def redirect_unless_admin
    unless current_user.is_admin?
      redirect_to root_path
    end
  end

end

app/views/categories/edit.html.erb
<%= form_for(@category)do |f| %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
      </div>
      <%= f.submit "Update", class: "btn btn-primary ml-3" %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="2">
        <span>
          <%= link_to "<i class='fa fa-plus' aria-hidden='true'></i> Create".html_safe, new_category_path, class: 'btn btn-sm btn-success' %>
        </span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |cat| %>
      <tr>
        <td><%= cat.id %></td>
        <td><%= cat.name %></td>
        <td>
          <span>
            <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i> Edit".html_safe, edit_category_path(cat), class: 'btn btn-sm btn-primary' %>
          </span>
          <span>
            <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i> Delete".html_safe, category_path(cat), method: :delete, class: 'btn btn-sm btn-outline-danger', data: {confirm: "Are you sure?"} %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="apple_pagination mx-auto">
  <%= paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<%= form_for(@category)do |f| %>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-md-6">
      </div>
      <%= f.submit "Create", class: "btn btn-primary ml-3" %>
    </div>
  </div>
<% end %>