config/routes.rb
Rails.application.routes.draw do
  # Use for login and autorize all resource
  use_doorkeeper do
    # No need to register client application
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users,
             only: [ :sessions, :passwords, :confirmation ],
             skip_helpers: true,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }
  resources :users do
    member do
      get :activate
    end
  end
  resources :categories
  resources :achievements

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
           registrations: 'api/v1/users/registrations',
       }, skip: [:sessions, :password]
    end
  end

  namespace :api do
    namespace :v1 do
      resource :dashboard
      resources :leagues do
        collection do
          get :pending
        end
      end
      resource :categories
      resources :achievements
      resources :user_achievements
      resource :profiles
    end
  end

  root to: 'dashboard#index'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <%= link_to "Wingmate",root_path, class: 'navbar-brand' %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <% if current_user.is_admin? %>
         <%= content_tag :li, class: "#{'active' if params[:controller] == 'users'} nav-item" do %>
          <%= link_to 'Users', users_path, class: 'nav-link' %>
         <% end %>

          <%= content_tag :li, class: "#{'active' if params[:controller] == 'categories'} nav-item" do %>
            <%= link_to 'Categories', categories_path, class: 'nav-link' %>
          <% end %>

          <%= content_tag :li, class: "#{'active' if params[:controller] == 'achievements'} nav-item" do %>
            <%= link_to 'Achievements', achievements_path, class: 'nav-link' %>
          <% end %>
        <% end %>
      </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wingmate</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <%= render partial: 'layouts/navigation' %>

    <div class="container-fluid mt-2">
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <%= yield %>
    </div>
    <%= custom_bootstrap_flash %>
  </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
      <title>Wingmate</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= csrf_meta_tags %>
    </head>
  </head>
  <body class="gray-bg">
    <!-- Main view  -->
    <%= yield %>
  </body>
</html>